By substitution method, we eliminate $t$,

$Y=-10(X / 20) 2+30(X / 20)+10=-(1 / 40) X 2+(3 / 2) X+10$

Using quadratic equation, $X 1, X 2=(3 / 2) /(1 / 20) \pm \sqrt{((3 / 2) 2+1)} /(-1 / 20)$

$=30 \pm 36.1 \rightarrow 66.1 \mathrm{~m}$

The distance is $66.1 \mathrm{~m}$ when the ball hits the ground. 

\[
\begin{array}{ll}
(X+2)^{2}=X^{2}+4 X+4 & X^{2}+10 X+25=(X+5)^{2} \\
(X-3)^{2}=X^{2}-6 X+9 & X^{2}-14 X+49=(X-7)^{2} \\
(X+2)(X+3)=X^{2}+5 X+6 & X^{2}+9 X+20=(X+4)(X+5) \\
\text { Write } X X \text { for } X^{2} \text { in the next section }
\end{array}
\]

\section{Write $X X$ for $X^{2}$ in the next section}

(1)

\[
\begin{aligned}
13 \times 15 &=(14=1)(14+1)=14^{2}-1 \\
14^{2} &=(10+4)^{2}=100+80+16=196 \text { Therefore, } 13 \times 15=195
\end{aligned}
\]

\[
\begin{aligned}
&18 \times 12=(15+3)(15-3)=15^{2}-3^{2}=225-9=216 \\
&27 \times 17=(20+7)(10+7)=200+70+140+49=459
\end{aligned}
\]